### ISSUE TITLE
Adapt to changes in ChimeraTK/DeviceAccess#117

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter#25]
Child of ChimeraTK/ApplicationCore#123

All the doXxxTransfer functions must not be called any more. You have to use xxxTransfer (without do) any  more. Currently the code does not even compile any more because the doXxxTransfer functions are now protected.

* [x] Make the code compile again
* [x] Check that doXxxTransfer functions  are not called anywhere else. A decorator might be allowed to access the protected function.
* [x] Check that all tests are still OK. There should be no functional change.
