### ISSUE TITLE
Adapt to changes in ChimeraTK/DeviceAccess#116

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter#26]
Child of ChimeraTK/ApplicationCore#123
Depends on ChimeraTK/DeviceAccess#116

Adapt to the changes in DeviceAccess:

* ChimeraTK/DeviceAccess#116 introduce API-breaking changes to postRead/Write. Add the new argument to the function overloads.
* Check whether the arguments should be used. For instance
  * don't generate a new version number in postRead if readTransferLatest did not get new data
  * when reading and the preRead() does not swap the user buffer, don't swap in postRead() becase the user buffer has to stay intact => no action if no new data
  * when the user buffer had been swapped in preWrite(), it always has to be swapped back in postWrite() => always action, even if dataLost is true

* [x] Extend the API so the code compiles again.
* [x] Check if you have to adapt functionality. No in this ticket where changes were made.
* Check that all tests are still OK.
  * [x] All existing tests should still pass.
  * [x] If you had to adapt the functionality check that there is a test for that behaviour

**Comment by ckampm** [comment]
Implementations to be adapted in this ticket:

* [ ] `BidirectionalProcessArray<T>::doPostRead`: Version number update
* [ ] `BidirectionalProcessArray<T>::doReadTransferAsync`: Set `hasNewData` in `postRead` call
* [ ] `TypeChangingDecorator::doPostRead`: User buffer swap in `convertAndCopyFromImpl` 
* [ ] `testTypeChangingDecorator.cpp`: Pass new parameter to postReadWrite in the `testDecorator` function
* [ ] `UnidirectionalProcessArray<T>::doPostRead`: Version number update and user buffer swap

**Comment by killenb** [comment]
Please also check for side effects of ChimeraTK/DeviceAccess#117:
* [ ] If a decorator delegates the postAction and does something after it in the override of doPostXxx(), it might need a try-catch block, to the stuff and re-throw

**Comment by killenb** [comment]
I removed the urgent flag. The urgent part was to make it compile again.
